In [1]:
lst1 = ['Ahmed', 28, 50000.0]
lst2 = ['Ali', 25, 45000.0]

In [2]:
print(lst1)

['Ahmed', 28, 50000.0]


In [3]:
new = ['a', 'b', 'c','d']

In [4]:
for i in new:
    print(i)

a
b
c
d


In [7]:
lst3 = [lst1, lst2]  # list of list

In [6]:
print(lst3)

[['Ahmed', 28, 50000.0], ['Ali', 25, 45000.0]]


In [123]:
lst1 = ['Ahmed', 28, 50000.0]
lst2 = ['Ali', 25, 45000.0]
lst3 = [lst1, lst2]
print(lst3[0][2])

50000.0


In [11]:
for i in lst3:
    print(i[0])

Ahmed
Ali


In [9]:
i = ['Ahmed', 28, 50000.0]

In [10]:
print(i[0])

Ahmed


In [12]:
## dictionary   >>>>> {}  >>>>> { key : value }
emp1 = {'name' : 'Ahmed', 'age' : 28, 'salary' : 500000.0}

In [13]:
print(emp1['name'])

Ahmed


In [14]:
print(emp1['salary'])

500000.0


In [15]:
employees = {'name' : ['Ahmed', 'Anas', 'Ali'], 'age' : [28, 25, 26], 'salary' : [45000, 60000, 50000]}

In [16]:
print(employees['name'])

['Ahmed', 'Anas', 'Ali']


In [17]:
print(employees['salary'])

[45000, 60000, 50000]


In [126]:
lst = ['kaaif', 'mohammed']
lst.insert(1, 'haris')
print(lst)

['kaaif', 'haris', 'mohammed']


In [18]:
lst1.append('Karachi')

In [19]:
print(lst1)

['Ahmed', 28, 50000.0, 'Karachi']


In [20]:
lst1.pop(3)

'Karachi'

In [21]:
lst1

['Ahmed', 28, 50000.0]

In [22]:
lst1.append('Karachi')

In [23]:
lst1

['Ahmed', 28, 50000.0, 'Karachi']

In [24]:
lst1.remove('Karachi')

In [25]:
lst1

['Ahmed', 28, 50000.0]

In [39]:
type(50.0544)

float

In [58]:
type(50) == int

True

In [52]:
import numpy as np

In [54]:
type(np.int16(12))

numpy.int16

In [57]:
# a = input('Enter any number: ')
# if type(a) == int:
#     print('integer')
# else:
#     print('float')

Enter any number: 50
float


In [43]:
"." in "20.56"

True

In [60]:
a = input('Enter any number: ')
if "." in a:
    print('float')
else:
    print('int')

Enter any number: 45.55
float


In [3]:
# !pip install numpy

In [5]:
import numpy as np

In [10]:
lst = [1,4,5,7,9,23,11,10]

In [11]:
np.sum(lst)

70

In [108]:
a = 2
b = 3

In [110]:
np.sum(a)

2

In [12]:
np.max(lst)

23

In [13]:
np.argmax(lst)

5

In [14]:
np.argmin(lst)

0

In [23]:
np.random.randint(2,15)

4

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
lst = ['ali', 'hamza', 'asad', 'noman']

In [25]:
for i in lst:
    print(i)

ali
hamza
asad
noman


In [26]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [113]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
lst = []
a = int(input("Enter a number: "))
lst.append(a)

Enter a number: 2


In [30]:
lst

[2]

In [36]:
lst = []
for i in range(10):
    a = int(input(f"Enter {i+1} number: "))
    lst.append(a)

In [33]:
lst

[2, 3, 7, 4, 89, 44, 7, 22, 4, 6]

In [50]:
employess = {'names':[], 'age':[], 'weight':[]}

i = 1
b = 1
d = 1
e = 1

while i == 1:

    a = input("Enter the names : ")
    employess["names"].append(a)
    b += 1
    print(b)
    if b > 5:

        c = input("Enter the ages : ")
        employess["age"].append(c)
        d += 1
        if d > 5:
            f = input("Enter the weights : ")
            e += 1
            if e == 5:
                break

Enter the names : k
2
Enter the names : k
3
Enter the names : k
4
Enter the names : k
5
Enter the names : k
6
Enter the ages : k
Enter the names : k
7
Enter the ages : 54


KeyboardInterrupt: Interrupted by user

In [46]:
print(employess)

{'names': ['ali', 'kashan', 'kaaif', 'asad', 'noman'], 'age': [], 'weight': []}


In [55]:
employess = {'names':[], 'age':[], 'weight':[]}
lst = ['names', 'age', 'weight']

for i in lst:
    for j in range(5):
        a = input(f'Enter {i}: ')
        employess[i].append(a)

Enter names: f
Enter names: g
Enter names: h
Enter names: j
Enter names: t
Enter age: 5
Enter age: 6
Enter age: 7
Enter age: 89
Enter age: 4
Enter weight: 6
Enter weight: 3
Enter weight: 23
Enter weight: 2
Enter weight: 2


In [56]:
employess

{'names': ['f', 'g', 'h', 'j', 't'],
 'age': ['5', '6', '7', '89', '4'],
 'weight': ['6', '3', '23', '2', '2']}

In [71]:
a = [1,13,5]
b = [7,99,11]

a = np.array(a)
b = np.array(b)


print(np.concatenate((a,b)))

print(np.sort(a))


[ 1 13  5  7 99 11]
[ 1  5 13]


In [72]:
# ndim ---> dimensions
a.ndim

1

In [73]:
c = np.array(
    [
    [2,3,4],
    [5,6,7]
]
)

In [74]:
c.ndim

2

In [76]:
a = [1,13,5,10]

a = np.array(a)

In [77]:
a.shape

(4,)

In [79]:
a.reshape(2,2)

array([[ 1, 13],
       [ 5, 10]])

In [84]:
def myfunc(name):
    print("Hello my name is " + name)

In [85]:
myfunc('ahsan')

Hello my name is ahsan


In [101]:
class Solve:
    def __init__(self, num):
        self.num = num

    
    def summ(self):
        print(self.num + 10)
        
    def diff(self):
        print(self.num-10)

In [102]:
Solve(20).summ()

30


In [103]:
Solve(20).diff()

10


In [104]:
class Solve:
    def __init__(self, num):
        self.num = num

    
    def summ(self, num2):
        print(self.num + 10 + num2)
        
    def diff(self):
        print(self.num-10)

In [105]:
Solve(50).summ(10)

70


In [106]:
class Solve:
    def __init__(self, num):
        self.num = num

    
    def summ(self, num2):
        print(10 + num2)
        
    def diff(self):
        print(num-10)

In [107]:
Solve().summ(10)

20


In [2]:
barfoo = []
barfoo.append('2')
barfoo.append('1')
barfoo.append('+')
barfoo.append('5')
print(''.join(barfoo))

21+5


In [5]:
eval('12-6+5')

11

In [ ]:
4 sq 

In [7]:
4 ** 0.5

2.0

In [9]:
len('')

0

In [15]:
eval('0o1+5')

6

In [27]:
equation = ['2','3','4']

In [28]:
'[0-9]'

'[0-9]'

In [29]:
equation[-1] in '123456789'

True

In [31]:
t = '1.5555.'

In [34]:
t.count('.')

2

In [48]:
ll = ['.','1','.', '+','-']

In [40]:
for i in '+-*/':
    print(i)

+
-
*
/


In [58]:
l = ['+','-','*']

In [52]:
[x for x in '+-*/' if x in ll]

['+', '-']

In [59]:
l.split('1')

AttributeError: 'list' object has no attribute 'split'

In [61]:
lst = ['5','+','5','*','2.5', '-', '2']

In [67]:
strr = ''.join(lst)

In [85]:
strr

'5+5*2.5-2'

In [70]:
import re

In [82]:
re.split('\+ |\- |\*',strr)

['5+5', '2.5-2']

In [84]:
a='Beautiful- is+ better*than\nugly'
import re
re.split('\+ |- |\*|\n',a)

['Beautiful', 'is', 'better', 'than', 'ugly']

In [92]:
re.split('\+|\*|-', strr)

['5', '5', '2.5', '2']

In [97]:
a = [1, 2, 2, '+']
a[-1].isdigit()

False

In [ ]:
y = 2x
y = 5x + 3
y = 7x - 3x + 8

In [106]:
import re
strr = '2+2-2/2*2'
lst = re.split('[+*\-√/]', strr)
print(lst)

['2', '2', '2', '2', '2']


In [1]:
st = '\n 1 | 2 | 3 \n-----------\n 4 | 5 | 6 \n-----------\n 7 | 8 | 9 \n'

In [7]:
if '5' in st:
    st = st.replace('5', 'X')

In [8]:
st

'\n 1 | 2 | 3 \n-----------\n 4 | X | 6 \n-----------\n 7 | 8 | 9 \n'

In [9]:
'5' in st

False

In [10]:
st.replace('5', 'X')

'\n 1 | 2 | 3 \n-----------\n 4 | X | 6 \n-----------\n 7 | 8 | 9 \n'

In [28]:
Tablee = '\n   |   |   \n-----------\n   |   |   \n-----------\n   |   |   \n'
o = 0
for i in Table:
    print(i, o)
    o += 1



 0
  1
1 2
  3
| 4
  5
2 6
  7
| 8
  9
3 10
  11

 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23

 24
  25
4 26
  27
| 28
  29
5 30
  31
| 32
  33
6 34
  35

 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47

 48
  49
7 50
  51
| 52
  53
8 54
  55
| 56
  57
9 58
  59

 60


In [12]:
Table = '\n 1 | 2 | 3 \n-----------\n 4 | 5 | 6 \n-----------\n 7 | 8 | 9 \n'
o = 0
for i in Table:
    print(i, o)
    o += 1


 0
  1
1 2
  3
| 4
  5
2 6
  7
| 8
  9
3 10
  11

 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23

 24
  25
4 26
  27
| 28
  29
5 30
  31
| 32
  33
6 34
  35

 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47

 48
  49
7 50
  51
| 52
  53
8 54
  55
| 56
  57
9 58
  59

 60


In [13]:
Table = '\n 1 | 2 | 3 \n-----------\n 4 | 5 | 6 \n-----------\n 7 | 8 | 9 \n'

In [14]:
Table[0]

'\n'

In [ ]:
1 2  3   4  5  6   7   8  9

2 6 10  26 30 34   50 54 58

In [15]:
dictt = {1:2, 2:6, 3:10, 4:26, 5:30, 6:34, 7:50, 8:54, 9:58}

In [16]:
dictt[1]

2

In [25]:
st.replace(st[20],'X', 1)

'\n 1 | 2 | 3 \nX----------\n 4 | X | 6 \n-----------\n 7 | 8 | 9 \n'

In [20]:
st

'\n 1 | 2 | 3 \n-----------\n 4 | X | 6 \n-----------\n 7 | 8 | 9 \n'

In [31]:
string = st
position = 34
new_character = 'X'

st[:position] + new_character + st[position+1:]


'\n 1 | 2 | 3 \n-----------\n 4 | X | X \n-----------\n 7 | 8 | 9 \n'

In [6]:
face_dis = [0.4, 0.7, 0.1333
           ]
round(100 - (min(face_dis) * 100), 2)

86.67